name: Lint & Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: Lint with Ruff
        run: |
          ruff check .

      - name: Lint with Black
        run: |
          black --check .

  test:
    strategy:
      matrix:
        python_version: ["3.10", 3.11, 3.12]
        django_version: [4.0, 4.1.0, 4.2.2, 5.0, 5.1]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q Django==${{ matrix.django_version }}
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements/test.txt; fi

      - name: Run tests
        run: |
          python manage.py test t.unit
